language: node_js
node_js:
- '10'
env:
  global:
  - secure: VATOqLqYGRCNc7jSIDlFH/gVk4/dhj1O7uhPWf44PZKpgL0PCCJ6+HWiV4+/MpW6UUXoqsLRUUXioAQp9JbPXItPkyYjHyT+U45USMcIJEhKh8FjS1Jyunr6F4oN4tpr8OP/2chTqoIAvDhiQm4wuc2ww3bdQxgIYG/w479PwWDNlVgjdMP5ohwuyHVCDBe9+9mhIXUsnUda7a+DaGVnMQ5lU1D02XhzmhFUc9DAIGdCZmWUUnMlS4ZCWWwNBPrxxMvGafLgc6u93pG7XchV3PbQLBltpY+HH8DGGrk67arkLPAsCkRIfQ89LwzSncQbq42IETAxXiQgT9L3/f78qWYP+is0ssS94ho8Qr+LWXMjooHaq0+tvl4JVWpdHd2nWiOz/8G17XB5cRG5L1R96u4Q0Xm/fc+yso/DPnUqoGJAL9rF2yigjLCdlmkXaXHZHcm9dARj1PEOT1yg3YNLkx+DGa92IzKbR37uNPz7ulGMP5yTCYaXLe/zQWrGVMph7ZCoYxP+PTJgHmEzy+e33oLeJtmqyj0kyK1ZAgjmdv8WHrbyBbWTgtzcoWRqrbLNdmBNBSCia1dHT6PMxXpHaRJp1e5Lht0lhxbmABLON9as9yqhST0Dv/N6ptYJdWUp0h6KtHUGBmPb+LXchkxDJFx4rb6QCHacSbwDAbbbfIk=
  - secure: R3M+LD/T9SabhJPSzBc6FRW2cPxw9RLMWHtxVZC6XijaCF9x/bJXcXythgz7iddEBrJ1B74b9qGbOlFiLH7FDee3OGRPxg4P62OrUbcM6+2+EJ0HUntfGCxlEiXAQcqaVBJgMaT9Mr2U/hqYi03NWzEyyvQyUtNc62NT/yZvATs6vowSFrsPFYQNLamqQDRyoFaP+ZMvkNuVMwh22tw4vKiADevlMX/9iT49kKPgphQvy+MmY9plvBMrCLdCCD8CrMfvMlEfEHwYY65tsGTMIH2MP67+4nm6QO1cAlp6uxcu3roHU1hBJOwvvPSD4KweMKAh3C9mt4v+atHPMfx449vFmOaYD3pYUzr4t5OimuDtW7voT4ruIO8NwAmwT/QH55vTj41W7leRlKVzaurch7B11drE6xQsGbsMGdKY2UtNR3RKjA7dZl7Sgk22PIravNI8FmT6Nrb4cj1u+g+tW2wPIEzo35W/emQ3tpySRnKxKVjMwlC530kQ2UcrcywzsePJgoI3XTjjXSVRBW07Sho8qTje03/IJfIKHQxRftRhYvrAy7nrfhGwsCmRHK9qI17LGKzIJnsxDXBbMPdAJs41/tCVspRtAAfjCtLUbQZRB+Lz5Cx0eMMC0yEGiXs22k4TpC2DWVu5rh4neNVhcts48BVcCJmbw6ZbO5UDDdc=
  - secure: PF6nfNKcy3UqYCW1HPnptzjopqHOaMng8PDkOi/MaNgx6n5JMn/XGvav38j93SEyv2ldWmf8ckf3PGuIPwEdsvgEdEnSVrpWxPOWNK4mR7b8EGxBKkDz++kM4FaKxKDiphpHONzhkqgnZym+s9bnHiQbyX9+z/1+wnzYHiMU+pfmil0QP4ww+jmn8BggDy3XMKmrZdte3QMOUvKCw+bN5R8W/PQLrkA7P1FZ1tmEJqXB4GXLlj6bDO5cTKdkdZG21xbo6Fzn3AtfyghtPStKMkTQqKcz8J6znlJ8M8IbKMTFz5wwYOvlu1dehhIrwLf3Y96TYTh6PgaNsVq0xxEGwdxoRdxfcfhWGOeVBpYAmp304//SUsI0htzwPNfg7NA+qZ7afC0q920/gj1L+S76OgAvTQQYcuLW984MCpHdBNrO7s5JXwONdc6hjqwHyS8+WfBEfbcvrmzCcrEkEY0AC1kW4zXFwUg4N7LxYLa0qkpnBPw49koCrsMFRfOzDv3jT5ktFHlcIXW3QHi4jYTGCNWvq/8ukjatZ0SJjIzH/U0ICua3w8qiClxiSFCIKUOn/AKiT2HTFjkn45UwoiDm8vKtk7RXUZ0n9VEVraF+wfFfr0RXNvEWlWoO9xFvhffIx19Z/LUkKA1fvMcPO+jBXfN7+YJ2FG+WrA9ISUU7RMA=
  - secure: a+uNuQiId/4knF0Q69fe91uOm7EoiZvvQDOTiPP+5zs/CFBKvYnOsjr4A4/njwJpv9gnwS7/Trs04bBU+HRL1/79W8Y3GrvgudRCCjXgrDfjucB9xEykcdSQMxp9gul1Tu4noRv+EXN0DZ2WnUp2ec9WuUSkj1pX0eLPgvU0SDbstW8BTIQy6Bf6rj1MolBwt6QxVDNs0GpKQewjWEccLyR4vF/SiVcV+XYE+cPj+oYQ4YqzzDUGsurwP2CQvnENH9YDIubAhgZw0iq8VIlnWg0dNvkJDbvcsJULI/TGtBVJsQLmCeyhv25veMyp0ljfee8B8xqU3AN2et+v6BFcGJQxi5831btiEasJk+ewBJiMHwEHFY87kcHEb3LKRusdhaEEAkMSXnl0YMeEJWbFo4C/m3iPeiQ9LR1nHFmpwbeLsesuluDS9mx9W9cHqD6Elyc9U2clDqJ7r4XgaUsNaiusEPZz3XR+EpZn4zIccTmiynZ5Wx1KM2Zi81qlNAKWKfiOlVoNCp35jdBdEXsneQiW0fym/4gEy98OxzgMmpx1faPSiPaM8eg0wjKKa7q06VifBE4Eehj0oE3EXJOyJ1OSRog3Tm5OU14yEp7sRvLftJKwULO0/Xc4Q+R0NYh9xc0q5GRcg4rVPvEgDutZ+LqhdYQy/wYXyhCfddbb27g=
matrix:
  include:
  - name: Frontend
    before_install:
    - cd client
    - npm install
    - npm install -g vue-cli
    script:
    - npm run lint
    - npm run build
    before_deploy:
    - echo -e "Building master branch - Deploying client..."
    - echo $DEPLOY_SERVER 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEA3GjJpKzSA2ljAzu0I0jETK+cq0licx7PbnDBPIFlaeKOGrEbpLxoH4nM03bfLqj1ymuJv0kwf2M9JiYheeEgLzBwzB26/W2iIj+ojksQJkJVt10EI7esl+mISQeKxHEWzjxLZx8498P+/kOMtI6WQbgT/byanaEgUztNdFCYpx2QVcwPxEAxqEtIfMQZPHrGrMqnaEQ+dV5oM/Qj0+MmmG7lmOa3flS4StjRjKbgoTRNi8Zk97z1eo6liwU8NTdU5bAUtja+7jPcqljRmoqKo2nZFsKnZ+aDYTRXp08sCBujh98dH2cxeu7wcgcAm96f/uPyOTBz8qz0+AgYS/TbV2jMqDI/qKMZ9MR89tNapbpF4XBc9gbq9ZT7G9+KbyRbGSMrZkSZNmm9OoNH8kDyOxOxjwlMLxjxqWgUqSsr+gLyqW2Cp1Dw7h80AofTG1ksdSRq8/AtPdXoivJXCEQwCLbFCQAZGJG/U67LS+6fwOwwessQSj6xuYY068D81KUSTvBus2hbG3EiGPHhv+S0WH1VdymE1kNcB6T9knTWb4ElrPWFOI7Awcei2rIWR+80ADMhbCnM9F3wzH2aQPnV6oexU92CeeeusaBkQd6Tm+J+bwhmlOVqZ4aGjWWyLMZgttJ65gIHlIqDQKFqeubypnIWTq2sW8LgwiQkK9woz60=' >> $HOME/.ssh/known_hosts
    - openssl aes-256-cbc -K $encrypted_c203fb406a06_key -iv $encrypted_c203fb406a06_iv -in $TRAVIS_BUILD_DIR/deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
    deploy:
      provider: script
      skip_cleanup: true
      script: >-
        ssh -p22 $DEPLOY_USER@$DEPLOY_SERVER "mkdir -p $CLIENT_DIR/_tmp" &&
        echo "RSYNC FRONTEND" &&
        rsync -rav -e ssh --exclude='.git/' --exclude=.DS_Store --delete-excluded $TRAVIS_BUILD_DIR/client/dist/* $DEPLOY_USER@$DEPLOY_SERVER:$CLIENT_DIR/_tmp &&
        echo "REMOVE OLD FILES" &&
        ssh -p22 $DEPLOY_USER@$DEPLOY_SERVER "cd $CLIENT_DIR && rm -r !(_tmp) && mv $CLIENT_DIR/_tmp/* $CLIENT_DIR && rm -rf $CLIENT_DIR/_tmp"
      on:
        branch: master
  - name: Server
    before_install:
    - cd api
    - npm install
    script:
    - npm run build
    before_deploy:
    - echo "Building master branch - Deploying server..."
    - echo $DEPLOY_SERVER 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEA3GjJpKzSA2ljAzu0I0jETK+cq0licx7PbnDBPIFlaeKOGrEbpLxoH4nM03bfLqj1ymuJv0kwf2M9JiYheeEgLzBwzB26/W2iIj+ojksQJkJVt10EI7esl+mISQeKxHEWzjxLZx8498P+/kOMtI6WQbgT/byanaEgUztNdFCYpx2QVcwPxEAxqEtIfMQZPHrGrMqnaEQ+dV5oM/Qj0+MmmG7lmOa3flS4StjRjKbgoTRNi8Zk97z1eo6liwU8NTdU5bAUtja+7jPcqljRmoqKo2nZFsKnZ+aDYTRXp08sCBujh98dH2cxeu7wcgcAm96f/uPyOTBz8qz0+AgYS/TbV2jMqDI/qKMZ9MR89tNapbpF4XBc9gbq9ZT7G9+KbyRbGSMrZkSZNmm9OoNH8kDyOxOxjwlMLxjxqWgUqSsr+gLyqW2Cp1Dw7h80AofTG1ksdSRq8/AtPdXoivJXCEQwCLbFCQAZGJG/U67LS+6fwOwwessQSj6xuYY068D81KUSTvBus2hbG3EiGPHhv+S0WH1VdymE1kNcB6T9knTWb4ElrPWFOI7Awcei2rIWR+80ADMhbCnM9F3wzH2aQPnV6oexU92CeeeusaBkQd6Tm+J+bwhmlOVqZ4aGjWWyLMZgttJ65gIHlIqDQKFqeubypnIWTq2sW8LgwiQkK9woz60=' >> $HOME/.ssh/known_hosts
    - openssl aes-256-cbc -K $encrypted_c203fb406a06_key -iv $encrypted_c203fb406a06_iv -in $TRAVIS_BUILD_DIR/deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
    deploy:
      provider: script
      skip_cleanup: true
      script: >-
        ssh -p22 $DEPLOY_USER@$DEPLOY_SERVER "mkdir -p $SERVER_DIR/_tmp" &&
        echo "STOP SERVER AND REMOVE OLD SERVER FILES" &&
        ssh -p22 $DEPLOY_USER@$DEPLOY_SERVER "cd $SERVER_DIR && rm -r !(config.js|node_modules|_tmp)" &&
        echo "RSYNC SERVER" &&
        rsync -rav -e ssh --exclude='.git/' --exclude=.DS_Store --delete-excluded $TRAVIS_BUILD_DIR/api/dist/server.js $TRAVIS_BUILD_DIR/api/package.json $DEPLOY_USER@$DEPLOY_SERVER:$SERVER_DIR/_tmp &&
        echo "INSTALL NEW DEPS" &&
        ssh -p22 $DEPLOY_USER@$DEPLOY_SERVER "svc -d ~/service/wand-server && cd $SERVER_DIR && rm -r !(_tmp) && mv $SERVER_DIR/_tmp/* $SERVER_DIR && rm -rf $SERVER_DIR/_tmp && npm install && svc -u ~/service/wand-server"
      on:
        branch: master
